{% set version = "0.7.1" %}
{% set sha256 = "c8df019d5a12613245db2e5ed1e11efa20e5b8870e3b0c9c030e2ceddf96b807" %}

package:
  name: datreant.core
  version: {{ version }}

source:
  fn: datreant.core-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/datreant.core/datreant.core-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - asciitree
    - pathlib2
    - scandir
    - six
    - fuzzywuzzy
    - python-levenshtein
    - datreant <=1.0

test:
  imports:
    - datreant.core
    - datreant.core.backends
    - datreant.core.tests
  requires:
    - pytest

about:
  home: http://datreant.org/
  license: BSD 3-Clause
  summary: 'persistent, pythonic trees for heterogeneous data'

extra:
  recipe-maintainers:
    - dotsdl
    - kain88-de
