travis:
  secure:
    BINSTAR_TOKEN: pviKI6x/9mbz5TunfPaSdS2Lrz7aYIYIuohg5QEes4hpNKQMEjWoX3DaF51VseX2+Aki6jdhOkrskTNOA+h44BVUFSkWmNzTpj9Nw4TCAe15Afilq1VSbq8ECgsTLIqWF1E+PiR3wQx7dbOccoILX7qP+PzV6W83rAfnuDypBlmIaXzGvIl35ugd4TesvRgoyecAUEAoB+7dbRy0sziNoLi/I7WVTkkegXdzcUrNpdVXaJlXVp6tJ1PTlCZSUHw5N04hYZm6ooFTVcW15kCrSwvoAn6c8JNBKBfOMIvLZZRB3iaJnTAS8yt0hcmY1u3tyBDNdqyZr4yzaK0MJHddex2A/Ug0mvChCO3rMrHeKc9HWNGbm9OhfpNDd6XNyshOwZkvgOqJh/3nJOfpPzqyCiNh+keR6mKDw+5rib/WwopX4i+thSxv7FVMzg8sPbUP8Jd2MrL+5cVjwwz+b6EMq9s5bC9MbY2N993DmQlpEqWR2E2e506OROZq1giw5m3czblRQGrgCxRhWTMDtJ4AbIK/dNX1VPacZCp4ECNCswHQlTIn1ezBXyRSCs0Y2Q/8CBLM+9Gu5qmFH5FmI0XR4Q7lZIE5XauSrKR9C6i3mPO5xVPnabWOYaQ+2696JJGt1SL5wWoptAFvUyGQ7ya9ltry5SqL0pxVV8Ibzm0MwaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
