travis:
  secure:
    BINSTAR_TOKEN: RQNkvbq+VJOCLEz082+ieZWzOxQt5hODMzdbcaHtDk/b/dRjS8JUJPbaZU2r9A3Tqh/5QaCPayqgpm3VW9VLzs0RIVxzGoV1PU1EP09ArG/nfwUgDjSHOjj8SKRb13dBblek7ZUCSuel2oauHNGaH2P/48iolPViA8WuRMCxJR//vWSgUAbfv/heApynlxr2ahvXacDLe80jO29Zti+UVUSknFqEfwpR7Yx3ATnDd5BbgQbVmI/4X3rKw6801bK0kpQXKfh42ib6O96Yw8Qpq6yv7OQwSEBSrTGgM8PYgqpnCWwZ1AItDkAgITZ+BOg/rpbRi6EDNLOmPJ0cLRyDWtP11HsZ/KzNO8Ip38dfW0Z7FAjwJSgCPsB4wRv0sgHs88+XAkKp3s7hO6R7UtdsBoQZUe/izGhXWPK2lpi/mFdt7D6AaHkU63jVRA/8oFrmI/muJfmgGny+16CVnkscrdpNWiG/9CUVnjxyVgXfKxwYYlVsn1k+G0GoysL+A0GPBbge3yexyUFrmntZIBiL1nwkH30NRuGXJPzP9xH/WFiB2VeI/573OrPyQ2eNhV3yKPPUvnCyt9+ShJBxhP3KK0sKUCE+c/P4XDOIvSEPU+mQwpDpio0qPRBY2jKowmjOL7ySX1gwrDXYowR+Im6Rne1L/m9WkNTcnFvtlS7pAJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
